# This is a basic workflow to help you get started with Actions

name: termux-build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ termux ]
  pull_request:
    branches: [ termux ]
  

# A workflow run is made up of one or more jobs that can run 
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      version: 25
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Run aarch64 build
      run: |
        echo Start building.
        mkdir -p termux/data/data/com.termux/files
        cd termux/data/data/com.termux/files
        mkdir home usr
        cd usr/
        wget -Obootstrap-aarch64-v${version}.zip https://bintray.com/termux/bootstrap/download_file?file_path=bootstrap-aarch64-v${version}.zip
        unzip bootstrap-aarch64-v${version}.zip
        ls
