name: termux-build

on:
  push:
    branches: [ termux ]
  pull_request:
    branches: [ termux ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      version: 25
    steps:
    - uses: actions/checkout@v2
    - name: Run build
      run: |
          bash termux-build.sh aarch64 24
          bash termux-build.sh arm 24
          bash termux-build.sh i686 24
          bash termux-build.sh x86_64 24
          bash termux-build.sh aarch64 21
          bash termux-build.sh arm 21
          bash termux-build.sh i686 21
          bash termux-build.sh x86_64 21
    - name: Upload artifacts of aarch64
      uses: actions/upload-artifact@v1
      with:
        name: rootfs-termux24-aarch64.tar.gz
        path: ./termux/build/rootfs-termux24-aarch64.tar.gz
    - name: Upload artifacts of arm
      uses: actions/upload-artifact@v1
      with:
        name: rootfs-termux24-arm.tar.gz
        path: ./termux/build/rootfs-termux24-arm.tar.gz
    - name: Upload artifacts of i686
      uses: actions/upload-artifact@v1
      with:
        name: rootfs-termux24-i686.tar.gz
        path: ./termux/build/rootfs-termux24-i686.tar.gz
    - name: Upload artifacts of x86_64
      uses: actions/upload-artifact@v1
      with:
        name: rootfs-termux24-x86_64.tar.gz
        path: ./termux/build/rootfs-termux24-x86_64.tar.gz
    - name: Upload artifacts of aarch64(21)
      uses: actions/upload-artifact@v1
      with:
        name: rootfs-termux21-aarch64.tar.gz
        path: ./termux/build/rootfs-termux21-aarch64.tar.gz
    - name: Upload artifacts of arm(21)
      uses: actions/upload-artifact@v1
      with:
        name: rootfs-termux21-arm.tar.gz
        path: ./termux/build/rootfs-termux21-arm.tar.gz
    - name: Upload artifacts of i686(21)
      uses: actions/upload-artifact@v1
      with:
        name: rootfs-termux21-i686.tar.gz
        path: ./termux/build/rootfs-termux21-i686.tar.gz
    - name: Upload artifacts of x86_64(21)
      uses: actions/upload-artifact@v1
      with:
        name: rootfs-termux21-x86_64.tar.gz
        path: ./termux/build/rootfs-termux21-x86_64.tar.gz

